"""created the Restaurant model/table

Revision ID: 680af9e7523c
Revises: 69e91f3b8623
Create Date: 2023-09-23 15:01:21.430411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680af9e7523c'
down_revision = '69e91f3b8623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurants')
    # ### end Alembic commands ###
