"""added  the restaurant_pizzas  model/table

Revision ID: 923cb1980eb9
Revises: 65ec46a2095d
Create Date: 2023-09-23 15:10:10.707508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923cb1980eb9'
down_revision = '65ec46a2095d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_pizzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_pizzas')
    # ### end Alembic commands ###
