"""added the name length and unique  constraints to the restaurants table 

Revision ID: 56a6519113ab
Revises: 9f5540eb6bcb
Create Date: 2023-09-23 18:50:18.476847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a6519113ab'
down_revision = '9f5540eb6bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_restaurant_name', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['unique_restaurant_name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('unique_restaurant_name')

    # ### end Alembic commands ###
